### PR TITLE
bump to minecraft 1.21.11

### PR DESCRIPTION
**Pull request by walmartdog**
this PR updates fastback dependencies to fix a crash caused by fabric-permissions-api-v0 on minecraft 1.21.11 (NoClassDefFoundError)

- loom from 1.11 to 1.13
- fabric-permissions-api from 0.5.0 to 0.6.1
- fabric loader from 0.17.3 to 0.18.2
- fabric api from 0.138.3 to 0.139.4
- architectury from 18.0.6 to 18.0.8
- changed fastback version from 0.29.1 to 0.30.0 cus why not

only loom and fabric-permissions-api changes were necessary to prevent crash but i went ahead and updated other dependencies as well. tested working on fabric 1.21.11 server

### CODE REVIEW

**Comment by walmartdog** [comment]
added another commit, turns out architectury needs to stay at 18.0.6 or it breaks the in-game broadcast messages. my bad lol

**Comment by ChristianS2001** [comment]
@pcal43 would love to have this merged so we can get the 1.21.11 version for my server!

**Comment by karlbeecken** [comment]
@walmartdog thanks for bringing this forward, I just built it myself from your branch for 1.21.11, and it seems some message strings are not properly replaced:
image

**Comment by karlbeecken** [comment]
@walmartdog I found out the strings work with the new architectury 19.0.1 for 1.21.11, which was release a few days ago: https://github.com/architectury/architectury-api/commits/1.21.11

**Comment by walmartdog** [comment]
@karlbeecken oh snap. commit added thanks!

**Review by karlbeecken — APPROVED** [review]
Looks good to me, confirmed it working on fabric 1.21.11

**Comment by pcal43** [comment]
Thanks!
